git:
  quiet: true
  depth: 300
language: node_js
node_js:
- 10
before_install:
- echo '7.1' > ~/.phpenv/version
- php --version
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
- export PATH="$HOME/.yarn/bin:$PATH"
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- ssh git@github.com || true
install:
- if [ "$TRAVIS_TAG" = "" ]; then yarn install --frozen-lockfile; fi

script:
- ./scripts/ci.sh
cache:
  npm: true
  yarn: true
  directories:
    - ~/.cache
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: NOl9X8wciJFdhNXSfVSboQVWgZZyUBEwVyxCqzwmMtpSJptk31UxFeS+vxnzBtW3VmUYcadOfltmtQmgCaeL7DyJMexE++wQHtPnwQENNBUK3MmwcuL6vmPtMTaVr0lEDPvlpZh+1ZkXwIgutqYoElK/aMMwMrPvkdx+ZoATZQzDoozmF3YnI6kkd0S7KaWoXiAahkOleBdDbDz7fvgBZED2X4+aX1z1VpaIdB2+2mgv56x4cZf92KwVVskrxenAJtM20ie/8YTY3wY280M+6tCW3QqaoeWDJExZuRHHV1uOme39kEA2lORQGuP6EVsRLKf3m0a+pcLNUkSmWkKEvo4tFK7fAnLw+Eg73zb1H2cu+Y7bDptFRTKCgGpdHKy/Ay6FPzvxZMn66VKd+Gmv9cTBNb6hAzOIm6ozRzWQNXbQklJVg/MD+NTlfQlNRHyVjzUR29OqPQ+s0vgWk26pwAdTFHQ12g0XEj0ASJJ91mFI3z8h2UZXxSB3aOI2yT5+rv6KBVKLkXMa+/Ent7O1YAL4poYHVI/RxdvfNMpAUz1C+Cvqtx9d27kVGMviFSiAhdEhReGt21yjhUFp05rSEsul1PNAGd8AHZrmn5WGhjrUkBkAOOGwk2mJFuYi+imCPGpe0ZCsyqI9D0cP/SCwpdH7+Ax/hQGBjirEPBpXZSE=
